= Computer Science Fundamentals
:description: Some guidance on learning fundamentals of Computer Science

The easiest way to obtain CS  fundamentals is to get a formal education from a university.  That being said, there are wonderful resources available for free on the internet which can grant a wonderful foundation after sufficient effort.

Given that this is the osdev wiki, we will focus on those resources most needed for osdev.

== https://github.com/ossu/computer-science[Open Source Society University]
The OSSU has a complete CS curriculum of currated online materails.

It is recommened to follow the prerequisits even if you are already comfortable with them.  You can skim through them very quickly and you might learn something you had missed.

The following would be the bare minimum recommendation
=== Core CS, all
=== Core math, Mathematics for Computer Science
=== CS Tools, all
=== Core systems, all
=== Core theory, Divide and Conquer, Sorting and Searching, and Randomized Algorithms, Graph Search, Shortest Paths, and Data Structures
=== Advanced programming, Software Debugging

Highly recommended
=== Advanced systems, all

== https://ocw.mit.edu/[MIT Open Courseware]
Free course, many with lectures, from MIT!

https://ocw.mit.edu/courses/find-by-topic/#cat=engineering&subcat=computerscience[All computer science courses]
https://ocw.mit.edu/courses/mit-curriculum-guide/#map[Interactive map of prerequisits for each class]
